### ISSUE TITLE
2.4 problem?

### ISSUE THREAD

**Issue by drdamour** [michael/github#381]
i tried bumping to 2.4 and i'm getting an error about unable to locate/load github-api

**Comment by clayreimann** [comment]
Can you provide more detail? The error, your `package.json`, etc?

**Comment by WillBartee** [comment]
Second!

**Comment by nzakas** [comment]
I'm also seeing this. The exact error:

```
Error: Cannot find module 'github-api'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/Releases/Espree Release/espree/node_modules/eslint-release/lib/release-ops.js:18:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

The same code using `github-api` worked fine in v2.3.0.

**Comment by AurelioDeRosa** [comment]
The new release doesn't include changes in regard of how the files are compiled or references. It mostly add more methods. This must be an issue created by one of the dependency we have.

**Comment by clayreimann** [comment]
@AurelioDeRosa Could be because [the release build failed](https://travis-ci.org/michael/github/builds/160477498) we got checkstyled!

**Comment by AurelioDeRosa** [comment]
I used the usual `npm version minor` command.

**Comment by bot6830** [comment]
same problem here

**Comment by clayreimann** [comment]
`2.4.0` has been unpublished, we'll see if we can figure out what happened and push `2.4.1` when it's fixed.

For now you should be able to use the `2.3` line.

**Comment by klarkc** [comment]
@clayreimann still happening in the 2.3 version, and in the 2.2, I don't know about the build process, but the npm main file should not appoint to a built file, am I wrong?

**Comment by clayreimann** [comment]
I wonder if NPM changes something, because those versions certainly used to work...

Thanks,
Clay

**Comment by klarkc** [comment]
@clayreimann sorry about that, I found that you are deploying to dist in travis and pushing this folder to NPM repository. I was trying to use my fork instead of NPM repo, it's fixed xD

**Comment by drdamour** [comment]
so are we getting a 2.4.1?
